In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
spy = pd.read_csv(
    "../data/spy_market_data.csv",
    index_col="Date",
    parse_dates=True
)

spy.head()

,Adj Close,Close,High,Low,Open,Volume,return_1d,future_return_3d,target_3d
Date,,,,,,,,,
1993-01-29,24.113256,43.93750,43.96875,43.75000,43.96875,1003200,NaN,0.019915,1.0
1993-02-01,24.284769,44.25000,44.25000,43.96875,43.96875,480500,0.007113,0.016949,1.0
1993-02-02,24.336218,44.34375,44.37500,44.12500,44.21875,201300,0.002119,0.014094,1.0
1993-02-03,24.593472,44.81250,44.84375,44.37500,44.40625,529400,0.010571,0.003487,0.0
1993-02-04,24.696379,45.00000,45.09375,44.46875,44.96875,531500,0.004184,-0.007639,0.0

In [3]:
spy["return_3d"] = spy["Adj Close"].pct_change(3)
spy["return_5d"] = spy["Adj Close"].pct_change(5)
spy["return_10d"] = spy["Adj Close"].pct_change(10)
spy["return_20d"] = spy["Adj Close"].pct_change(20)

In [4]:
momentum_features = [
    "return_1d",
    "return_3d",
    "return_5d",
    "return_10d",
    "return_20d"
]

spy[momentum_features].tail(10)

            return_1d  return_3d  return_5d  return_10d  return_20d
Date
2026-08-14  -0.001980   0.007501   0.003983    0.039235    0.044465
2026-08-17  -0.004727   0.000233  -0.000466    0.019798    0.041208
2026-08-18  -0.006756  -0.013408  -0.004036   -0.005030    0.025619
2026-08-19   0.002098  -0.009377  -0.004440   -0.000948    0.028967
2026-08-20  -0.008400  -0.013033  -0.019643   -0.007755    0.033081
2026-08-21   0.004091  -0.002254  -0.013680   -0.009751    0.036255
2026-08-24  -0.002938  -0.007269  -0.011907   -0.012367    0.032986
2026-08-25   0.003196   0.004340  -0.002007   -0.006035    0.033812
2026-08-26   0.000222   0.000470  -0.003875   -0.008298    0.050202
2026-08-27   0.007793   0.011238   0.012392   -0.007495    0.040934

In [5]:
spy["sma_5"] = spy["Adj Close"].rolling(5).mean()
spy["sma_20"] = spy["Adj Close"].rolling(20).mean()

In [6]:
spy["price_vs_sma5"] = spy["Adj Close"] / spy["sma_5"] - 1
spy["price_vs_sma20"] = spy["Adj Close"] / spy["sma_20"] - 1

In [7]:
spy["sma5_vs_sma20"] = spy["sma_5"] / spy["sma_20"] - 1

In [8]:
trend_features = [
    "price_vs_sma5",
    "price_vs_sma20",
    "sma5_vs_sma20"
]

spy[trend_features].tail(10)

            price_vs_sma5  price_vs_sma20  sma5_vs_sma20
Date
2026-08-14       0.002946        0.026638       0.023623
2026-08-17      -0.001703        0.019723       0.021462
2026-08-18      -0.007650        0.011554       0.019352
2026-08-19      -0.004685        0.012232       0.016997
2026-08-20      -0.009127        0.002119       0.011349
2026-08-21      -0.002319        0.004451       0.006786
2026-08-24      -0.002860       -0.000100       0.002769
2026-08-25       0.000729        0.001453       0.000724
2026-08-26       0.001731       -0.000717      -0.002444
2026-08-27       0.007049        0.005080      -0.001955

In [9]:
spy["volatility_5d"] = spy["return_1d"].rolling(5).std()
spy["volatility_20d"] = spy["return_1d"].rolling(20).std()

In [10]:
spy["high_low_range"] = (
    spy["High"] - spy["Low"]
) / spy["Close"]

In [11]:
spy["volatility_ratio"] = (
    spy["volatility_5d"] / spy["volatility_20d"]
)

In [12]:
volatility_features = [
    "volatility_5d",
    "volatility_20d",
    "high_low_range"
]

spy[volatility_features].tail(10)

            volatility_5d  volatility_20d  high_low_range
Date
2026-08-14       0.004061        0.008416        0.004341
2026-08-17       0.004780        0.008519        0.005526
2026-08-18       0.005561        0.008601        0.003362
2026-08-19       0.005503        0.008583        0.005682
2026-08-20       0.004145        0.008289        0.008012
2026-08-21       0.005527        0.008304        0.004806
2026-08-24       0.005423        0.008366        0.004113
2026-08-25       0.005239        0.008372        0.004870
2026-08-26       0.005081        0.007362        0.004464
2026-08-27       0.004056        0.006688        0.006729

In [13]:
spy[
    [
        "volatility_5d",
        "volatility_20d",
        "volatility_ratio",
        "high_low_range"
    ]
].tail(10)

            volatility_5d  volatility_20d  volatility_ratio  high_low_range
Date
2026-08-14       0.004061        0.008416          0.482501        0.004341
2026-08-17       0.004780        0.008519          0.561133        0.005526
2026-08-18       0.005561        0.008601          0.646550        0.003362
2026-08-19       0.005503        0.008583          0.641205        0.005682
2026-08-20       0.004145        0.008289          0.500133        0.008012
2026-08-21       0.005527        0.008304          0.665520        0.004806
2026-08-24       0.005423        0.008366          0.648182        0.004113
2026-08-25       0.005239        0.008372          0.625777        0.004870
2026-08-26       0.005081        0.007362          0.690160        0.004464
2026-08-27       0.004056        0.006688          0.606415        0.006729

In [14]:
spy["overnight_gap"] = (
    spy["Open"] / spy["Close"].shift(1) - 1
)

spy["intraday_return"] = (
    spy["Close"] / spy["Open"] - 1
)

In [15]:
spy["volume_sma20"] = spy["Volume"].rolling(20).mean()

spy["volume_ratio"] = (
    spy["Volume"] / spy["volume_sma20"]
)

In [16]:
market_behavior_features = [
    "overnight_gap",
    "intraday_return",
    "volume_ratio"
]

spy[market_behavior_features].tail(10)

            overnight_gap  intraday_return  volume_ratio
Date
2026-08-14       0.000848        -0.002826      0.668479
2026-08-17      -0.000206        -0.004522      0.744923
2026-08-18      -0.005138        -0.001626      0.942491
2026-08-19       0.003792        -0.001688      0.858043
2026-08-20      -0.004031        -0.004387      0.979384
2026-08-21       0.004524        -0.000431      0.848262
2026-08-24      -0.001228        -0.001713      0.708914
2026-08-25       0.003523        -0.000326      0.612757
2026-08-26      -0.001541         0.001765      0.667434
2026-08-27       0.003159         0.004619      0.403295

In [17]:
volatility_features = [
    "volatility_5d",
    "volatility_20d",
    "volatility_ratio",
    "high_low_range"
]

feature_cols = (
    momentum_features
    + trend_features
    + volatility_features
    + market_behavior_features
)

print("Number of features:", len(feature_cols))
feature_cols

Number of features: 15

['return_1d',
 'return_3d',
 'return_5d',
 'return_10d',
 'return_20d',
 'price_vs_sma5',
 'price_vs_sma20',
 'sma5_vs_sma20',
 'volatility_5d',
 'volatility_20d',
 'volatility_ratio',
 'high_low_range',
 'overnight_gap',
 'intraday_return',
 'volume_ratio']

In [18]:
modeling_df = spy[
    feature_cols + ["target_3d"]
].copy()

modeling_df.shape

(8452, 16)

In [19]:
modeling_df.isna().sum()

return_1d            1
return_3d            3
return_5d            5
return_10d          10
return_20d          20
price_vs_sma5        4
price_vs_sma20      19
sma5_vs_sma20       19
volatility_5d        5
volatility_20d      20
volatility_ratio    20
high_low_range       0
overnight_gap        1
intraday_return      0
volume_ratio        19
target_3d            3
dtype: int64

In [20]:
modeling_df.head(22)

,return_1d,return_3d,return_5d,return_10d,return_20d,price_vs_sma5,price_vs_sma20,sma5_vs_sma20,volatility_5d,volatility_20d,volatility_ratio,high_low_range,overnight_gap,intraday_return,volume_ratio,target_3d
Date,,,,,,,,,,,,,,,,
1993-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004979,NaN,-0.000711,NaN,1.0
1993-02-01,0.007113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006356,0.000711,0.006397,NaN,1.0
1993-02-02,0.002119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.005638,-0.000706,0.002827,NaN,1.0
1993-02-03,0.010571,0.019915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.010460,0.001409,0.009148,NaN,0.0
1993-02-04,0.004184,0.016949,NaN,NaN,NaN,0.011947,NaN,NaN,NaN,NaN,NaN,0.013889,0.003487,0.000695,NaN,0.0
1993-02-05,-0.000695,0.014094,0.023471,NaN,NaN,0.006575,NaN,NaN,0.004368,NaN,NaN,0.007644,-0.000694,0.000000,NaN,0.0
1993-02-08,0.000000,0.003487,0.016243,NaN,NaN,0.003347,NaN,NaN,0.004524,NaN,NaN,0.004864,0.000000,0.000000,NaN,0.0
1993-02-09,-0.006949,-0.007639,0.007047,NaN,NaN,-0.005013,NaN,NaN,0.006479,NaN,NaN,0.005598,-0.003475,-0.003487,NaN,0.0
1993-02-10,0.001399,-0.005560,-0.002093,NaN,NaN,-0.003205,NaN,NaN,0.004105,NaN,NaN,0.004892,0.000000,0.001400,NaN,0.0
1993-02-11,0.004892,-0.000695,-0.001390,NaN,NaN,0.001951,NaN,NaN,0.004310,NaN,NaN,0.007650,0.001398,0.003489,NaN,0.0
1993-02-12,-0.007649,-0.001400,-0.008339,0.014936,NaN,-0.004048,NaN,NaN,0.005452,NaN,NaN,0.006307,-0.001391,-0.006267,NaN,0.0
1993-02-16,-0.025228,-0.027953,-0.033357,-0.017656,NaN,-0.022625,NaN,NaN,0.011664,NaN,NaN,0.024443,-0.002803,-0.022488,NaN,0.0
1993-02-17,-0.000718,-0.033379,-0.027292,-0.020437,NaN,-0.017945,NaN,NaN,0.011961,NaN,NaN,0.005755,0.000000,-0.000719,NaN,1.0
1993-02-18,-0.000719,-0.026629,-0.029349,-0.031380,NaN,-0.012793,NaN,NaN,0.011692,NaN,NaN,0.025918,0.011511,-0.012091,NaN,1.0
1993-02-19,0.003599,0.002157,-0.030598,-0.031945,NaN,-0.003004,NaN,NaN,0.011405,NaN,NaN,0.005022,0.000000,0.003600,NaN,1.0
1993-02-22,0.003587,0.006475,-0.019622,-0.027797,NaN,0.004596,NaN,NaN,0.012118,NaN,NaN,0.005004,0.002869,0.000715,NaN,1.0
1993-02-23,-0.000715,0.006479,0.005033,-0.028492,NaN,0.002869,NaN,NaN,0.002361,NaN,NaN,0.009299,0.002859,-0.003564,NaN,1.0
1993-02-24,0.012876,0.015782,0.018705,-0.009097,NaN,0.012007,NaN,NaN,0.005551,NaN,NaN,0.012006,0.000715,0.012152,NaN,0.0
1993-02-25,0.002119,0.014296,0.021598,-0.008385,NaN,0.009821,NaN,NaN,0.005110,NaN,NaN,0.005638,-0.000706,0.002827,NaN,1.0
1993-02-26,0.001409,0.016452,0.019368,-0.011822,NaN,0.007372,0.002999,-0.004341,0.005276,NaN,NaN,0.005630,0.002114,-0.000703,0.206205,1.0
1993-03-01,-0.002814,0.000706,0.012866,-0.007008,0.007824,0.001980,-0.000212,-0.002187,0.006073,0.007807,0.777961,0.007763,0.003519,-0.006311,0.242519,1.0
1993-03-02,0.014820,0.013389,0.028612,0.033789,0.015536,0.011109,0.013818,0.002679,0.007720,0.008328,0.927048,0.015299,0.000706,0.014104,0.703432,0.0

In [21]:
modeling_df_clean = modeling_df.dropna().copy()

print("Before:", modeling_df.shape)
print("After: ", modeling_df_clean.shape)

print("\nDate range:")
print(modeling_df_clean.index.min())
print(modeling_df_clean.index.max())

Before: (8452, 16)
After:  (8429, 16)

Date range:
1993-03-01 00:00:00
2026-08-24 00:00:00

In [22]:
#removing the last day

# Remove the current unfinished trading session
spy = spy.iloc[:-1].copy()

# Recompute the 3-day future return
spy["future_return_3d"] = (
    spy["Adj Close"].shift(-3) / spy["Adj Close"] - 1
)

# Recompute the target safely
spy["target_3d"] = np.nan

valid_target = spy["future_return_3d"].notna()

spy.loc[valid_target, "target_3d"] = (
    spy.loc[valid_target, "future_return_3d"] > 0.005
).astype(int)

In [23]:
modeling_df = spy[
    feature_cols + ["target_3d"]
].copy()

modeling_df_clean = modeling_df.dropna().copy()

print("Shape:", modeling_df_clean.shape)
print("Start:", modeling_df_clean.index.min())
print("End:  ", modeling_df_clean.index.max())

Shape: (8428, 16)
Start: 1993-03-01 00:00:00
End:   2026-08-21 00:00:00

In [24]:
X = modeling_df_clean[feature_cols].copy()
y = modeling_df_clean["target_3d"].astype(int).copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (8428, 15)
y shape: (8428,)

In [25]:
target_counts = y.value_counts()
target_pct = y.value_counts(normalize=True)

print("Counts:")
print(target_counts)

print("\nPercentages:")
print(target_pct)

Counts:
target_3d
0    4857
1    3571
Name: count, dtype: int64

Percentages:
target_3d
0    0.576293
1    0.423707
Name: proportion, dtype: float64

In [26]:
modeling_df_clean.to_csv(
    "../data/spy_modeling_data.csv"
)

print("Saved:", modeling_df_clean.shape)
print("Features:", len(feature_cols))
print("Start:", modeling_df_clean.index.min())
print("End:", modeling_df_clean.index.max())

Saved: (8428, 16)
Features: 15
Start: 1993-03-01 00:00:00
End: 2026-08-21 00:00:00