In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
    "../data/spy_modeling_data.csv",
    index_col="Date",
    parse_dates=True
)

df.shape

(8428, 16)

In [3]:
df.head()

,return_1d,return_3d,return_5d,return_10d,return_20d,price_vs_sma5,price_vs_sma20,sma5_vs_sma20,volatility_5d,volatility_20d,volatility_ratio,high_low_range,overnight_gap,intraday_return,volume_ratio,target_3d
Date,,,,,,,,,,,,,,,,
1993-03-01,-0.002814,0.000706,0.012866,-0.007008,0.007824,0.001980,-0.000212,-0.002187,0.006073,0.007807,0.777961,0.007763,0.003519,-0.006311,0.242519,1.0
1993-03-02,0.014820,0.013389,0.028612,0.033789,0.015536,0.011109,0.013818,0.002679,0.007720,0.008328,0.927048,0.015299,0.000706,0.014104,0.703432,0.0
1993-03-03,0.004173,0.016186,0.019774,0.038849,0.017618,0.011346,0.017152,0.005741,0.006591,0.008357,0.788662,0.004848,0.001391,0.002778,1.064048,1.0
1993-03-04,-0.005540,0.013408,0.011980,0.033837,0.001394,0.003354,0.011445,0.008065,0.007884,0.008151,0.967249,0.006964,0.001385,-0.006916,0.370992,1.0
1993-03-05,-0.002786,-0.004172,0.007741,0.027259,-0.005556,-0.000977,0.008912,0.009899,0.008232,0.008116,1.014345,0.009078,0.001393,-0.004172,0.184613,1.0

In [4]:
df.tail()

,return_1d,return_3d,return_5d,return_10d,return_20d,price_vs_sma5,price_vs_sma20,sma5_vs_sma20,volatility_5d,volatility_20d,volatility_ratio,high_low_range,overnight_gap,intraday_return,volume_ratio,target_3d
Date,,,,,,,,,,,,,,,,
2026-08-17,-0.004727,0.000233,-0.000466,0.019798,0.041208,-0.001703,0.019723,0.021462,0.004780,0.008519,0.561133,0.005526,-0.000206,-0.004522,0.744923,0.0
2026-08-18,-0.006756,-0.013408,-0.004036,-0.005030,0.025619,-0.007650,0.011554,0.019352,0.005561,0.008601,0.646550,0.003362,-0.005138,-0.001626,0.942491,0.0
2026-08-19,0.002098,-0.009377,-0.004440,-0.000948,0.028967,-0.004685,0.012232,0.016997,0.005503,0.008583,0.641205,0.005682,0.003792,-0.001688,0.858043,0.0
2026-08-20,-0.008400,-0.013033,-0.019643,-0.007755,0.033081,-0.009127,0.002119,0.011349,0.004145,0.008289,0.500133,0.008012,-0.004031,-0.004387,0.979384,0.0
2026-08-21,0.004091,-0.002254,-0.013680,-0.009751,0.036255,-0.002319,0.004451,0.006786,0.005527,0.008304,0.665520,0.004806,0.004524,-0.000431,0.848262,0.0

In [5]:
feature_cols = [
    col for col in df.columns
    if col != "target_3d"
]

X = df[feature_cols].copy()
y = df["target_3d"].astype(int).copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

print("Number of features:", len(feature_cols))

X shape: (8428, 15)
y shape: (8428,)
Number of features: 15

In [6]:
HORIZON = 3

train_df = df.loc[:"2018-12-31"].copy()
val_df = df.loc["2019-01-01":"2022-12-31"].copy()
test_df = df.loc["2023-01-01":].copy()

#Purging observations whose targets cross boundaries
train_df = train_df.iloc[:-HORIZON].copy()
val_df = val_df.iloc[:-HORIZON].copy()

In [7]:
for name, split_df in [
    ("TRAIN", train_df),
    ("VALIDATION",val_df),
    ("TEST", test_df)
]:
    print(f"\n{name}")
    print("Rows:",len(split_df))
    print("Start:", split_df.index.min())
    print("End: ",split_df.index.max())
    print("Positive target rate:", split_df["target_3d"].mean())

TRAIN
Rows: 6505
Start: 1993-03-01 00:00:00
End:  2018-12-26 00:00:00
Positive target rate: 0.41275941583397385

VALIDATION
Rows: 1005
Start: 2019-01-02 00:00:00
End:  2022-12-27 00:00:00
Positive target rate: 0.46567164179104475

TEST
Rows: 912
Start: 2023-01-03 00:00:00
End:  2026-08-21 00:00:00
Positive target rate: 0.4550438596491228

In [8]:
X_train = train_df[feature_cols].copy()
y_train = train_df["target_3d"].astype(int).copy()

X_val = val_df[feature_cols].copy()
y_val = val_df["target_3d"].astype(int).copy()

X_test = test_df[feature_cols].copy()
y_test = test_df["target_3d"].astype(int).copy()

print("TRAIN:", X_train.shape, y_train.shape)
print("VAL:  ", X_val.shape, y_val.shape)
print("TEST: ", X_test.shape, y_test.shape)

TRAIN: (6505, 15) (6505,)
VAL:   (1005, 15) (1005,)
TEST:  (912, 15) (912,)

In [9]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

In [10]:
dummy = DummyClassifier(strategy="most_frequent")

dummy.fit(X_train,y_train)

DummyClassifier(strategy='most_frequent')

In [11]:
dummy_val_pred = dummy.predict(X_val)

print("First 20 predictions:")
print(dummy_val_pred[:20])

print("\nUnique predictions:")
print(np.unique(dummy_val_pred))

First 20 predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Unique predictions:
[0]

In [12]:
dummy_val_accuracy = accuracy_score(
    y_val,
    dummy_val_pred
)

print("Dummy validation accuracy:", dummy_val_accuracy)

Dummy validation accuracy: 0.5343283582089552

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

log_reg = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))   
])

log_reg.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=1000))])

In [14]:
log_val_pred = log_reg.predict(X_val)

log_val_prob = log_reg.predict_proba(X_val)[:,1]

log_val_accuracy = accuracy_score(
    y_val,
    log_val_pred
)

log_val_auc = roc_auc_score(
    y_val,
    log_val_prob
)

print("Dummy accuracy:  ", dummy_val_accuracy)
print("LogReg accuracy: ", log_val_accuracy)
print("LogReg ROC-AUC:", log_val_auc)

Dummy accuracy:   0.5343283582089552
LogReg accuracy:  0.545273631840796
LogReg ROC-AUC: 0.5414060386127426

In [15]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(
    max_depth=4,
    min_samples_leaf=50,
    random_state=42
)

tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, min_samples_leaf=50, random_state=42)

In [16]:
tree_val_pred = tree.predict(X_val)

tree_val_prob = tree.predict_proba(X_val)[:,1]

tree_val_accuracy = accuracy_score(
    y_val,
    tree_val_pred
)

tree_val_auc = roc_auc_score(
    y_val,
    tree_val_prob
)

print("Dummy accuracy: ", dummy_val_accuracy)
print("LogReg accuracy:", log_val_accuracy)
print("LogReg AUC:     ", log_val_auc)
print()
print("Tree accuracy:  ", tree_val_accuracy)
print("Tree ROC-AUC:   ", tree_val_auc)

Dummy accuracy:  0.5343283582089552
LogReg accuracy: 0.545273631840796
LogReg AUC:      0.5414060386127426

Tree accuracy:   0.5492537313432836
Tree ROC-AUC:    0.5518013178627704

In [17]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_leaf=50,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=50, n_estimators=300,
                       n_jobs=-1, random_state=42)

In [18]:
rf_val_pred = rf.predict(X_val)
rf_val_prob = rf.predict_proba(X_val)[:,1]

rf_val_accuracy = accuracy_score(
    y_val,
    rf_val_pred
)

rf_val_auc = roc_auc_score(
    y_val,
    rf_val_prob
)

print("Random Forest accuracy:", rf_val_accuracy)
print("Random Forest ROC-AUC: ", rf_val_auc)


print("Dummy accuracy:", dummy_val_accuracy)

print("\nLogReg")
print("Accuracy:", log_val_accuracy)
print("AUC:     ", log_val_auc)

print("\nDecision Tree")
print("Accuracy:", tree_val_accuracy)
print("AUC:     ", tree_val_auc)

print("\nRandom Forest")
print("Accuracy:", rf_val_accuracy)
print("AUC:     ", rf_val_auc)

Random Forest accuracy: 0.5383084577114428
Random Forest ROC-AUC:  0.5521136736220534
Dummy accuracy: 0.5343283582089552

LogReg
Accuracy: 0.545273631840796
AUC:      0.5414060386127426

Decision Tree
Accuracy: 0.5492537313432836
AUC:      0.5518013178627704

Random Forest
Accuracy: 0.5383084577114428
AUC:      0.5521136736220534

In [19]:
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(
    learning_rate = 0.05,
    max_iter = 200,
    max_leaf_nodes = 15,
    min_samples_leaf =50,
    random_state= 42
)

hgb.fit(X_train,y_train)

HistGradientBoostingClassifier(learning_rate=0.05, max_iter=200,
                               max_leaf_nodes=15, min_samples_leaf=50,
                               random_state=42)

In [20]:
hgb_val_pred = hgb.predict(X_val)
hgb_val_prob = hgb.predict_proba(X_val)[:,1]

hgb_val_accuracy = accuracy_score(
    y_val,
    hgb_val_pred
)

hgb_val_auc = roc_auc_score(
    y_val,
    hgb_val_prob
)

print("Gradient Boosting accuracy:", hgb_val_accuracy)
print("Gradient Boosting ROC-AUC: ", hgb_val_auc)

Gradient Boosting accuracy: 0.545273631840796
Gradient Boosting ROC-AUC:  0.5450269779878718

In [21]:
from xgboost import XGBClassifier

In [22]:
xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.03,
    max_depth=3,
    min_child_weight=10,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, ...)

In [23]:
xgb_val_pred = xgb.predict(X_val)
xgb_val_prob = xgb.predict_proba(X_val)[:, 1]

xgb_val_accuracy = accuracy_score(
    y_val,
    xgb_val_pred
)

xgb_val_auc = roc_auc_score(
    y_val,
    xgb_val_prob
)

print("XGBoost accuracy:", xgb_val_accuracy)
print("XGBoost ROC-AUC: ", xgb_val_auc)

XGBoost accuracy: 0.5393034825870647
XGBoost ROC-AUC:  0.5462565057537125

In [24]:
results = pd.DataFrame({
    "Model": [
        "Dummy",
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "HistGradientBoosting",
        "XGBoost"
    ],
    "Accuracy": [
        dummy_val_accuracy,
        log_val_accuracy,
        tree_val_accuracy,
        rf_val_accuracy,
        hgb_val_accuracy,
        xgb_val_accuracy
    ],
    "ROC_AUC": [
        np.nan,
        log_val_auc,
        tree_val_auc,
        rf_val_auc,
        hgb_val_auc,
        xgb_val_auc
    ]
})

results.sort_values("ROC_AUC", ascending=False)

                  Model  Accuracy   ROC_AUC
3         Random Forest  0.538308  0.552114
2         Decision Tree  0.549254  0.551801
5               XGBoost  0.539303  0.546257
4  HistGradientBoosting  0.545274  0.545027
1   Logistic Regression  0.545274  0.541406
0                 Dummy  0.534328       NaN